### ISSUE TITLE
Parasite scollbar on fade away in windows

### ISSUE THREAD

**Issue by dy** [jossmac/react-toast-notifications#76]
https://gyazo.com/59c2b81baaa44fc106d1ca7027257156
At the very end, the disappearing items obtain a scrollbar there.

**Comment by jossmac** [comment]
@dy I don't have a windows machine handy to diagnose or address this issue, but I'd be happy to take a look at a PR.

Related #52

**Comment by THPubs** [comment]
I'm facing the same issue in Mac, Firefox.

**Comment by mendeel** [comment]
Sounds like a simple "overflow: hidden" is missing but I haven't investigated anything.

**Comment by Seanmclem** [comment]
I see it to on chrome/new-edge

**Comment by Seanmclem** [comment]
@jossmac any issue with my current PR for this?

**Comment by jossmac** [comment]
Resolved by #79

**Comment by impulse** [comment]
@jossmac I still have this issue on 2.4.0
OS: macOS 10.15.3 19D76 x86_64
Chrome: Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by jcloutz-radix** [comment]
@jossmac I am still getting this error as well. It looks like the currently published npm package does not contain this fix. Can you push a new release?

**Comment by Seanmclem** [comment]
@jcloutz-radix are you also on a Mac?

**Comment by jcloutz-radix** [comment]
@Seanmclem i am using mac and windows, there was no difference. In the published NPM package it's still `overflow: scroll`.
