### ISSUE TITLE
Deprecated findDOMNode usage 

### ISSUE THREAD

**Issue by mathieutu** [jossmac/react-toast-notifications#82]
There are warnings from react-toast-notifications with react strict mode enabled. This shows all the deprecated methods used.

https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by ToastElement)
    in ToastElement (created by DefaultToast)
    in DefaultToast (created by NamedToast)
    in NamedToast (created by ToastController)
    in ToastController (created by Transition)
    in Transition (created by ToastProvider)
    in TransitionGroup (created by ToastProvider)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by ToastContainer)
    in ToastContainer (created by ToastProvider)
    in ToastProvider
```

Thanks, 
Matt'

**Comment by jossmac** [comment]
Hi @mathieutu, could you tell me which version you're using?

There's no references to `findDOMNode` in the source, nor any dependencies that would employ that method.

**Comment by mathieutu** [comment]
> which version

v2.4.0

>nor any dependencies that would employ that method.

Found it! It comes from transition-group.

https://github.com/reactjs/react-transition-group/blob/616d95d2c48d1984b15730526e83fd39068fc181/src/Transition.js#L213

And here the PR which will remove it. https://github.com/reactjs/react-transition-group/pull/559

**Comment by jossmac** [comment]
@mathieutu great find, thank you! Just waiting for that PR to land

**Comment by olivierlemasle** [comment]
@jossmac https://github.com/reactjs/react-transition-group/pull/559 got merged today; upgrading to [react-transition-group version 4.4.0](https://github.com/reactjs/react-transition-group/releases/tag/v4.4.0) should remove the error message.

**Comment by jossmac** [comment]
@mathieutu @olivierlemasle I'm pretty jammed up with client work right now, happy to checkout a PR though

**Comment by mrcnk** [comment]
@jossmac here it comes: https://github.com/jossmac/react-toast-notifications/pull/116

**Comment by jasondana** [comment]
@mrcnk I could be wrong. But, I'm not sure changing the react-transition-group version is all that is necessary. I had been force updating the dependency version and was still receiving the warning. I took a look at it today and tried my hand at creating a patch to fix it completely. I don't want to overstep, so I have not submitted a competing pull request.

I found the error remained, even after updating the version of react-transition-group, because the Transition component requires a `nodeRef` property to be assigned that references the native element being transitioned. This is mentioned in their [change log](https://github.com/reactjs/react-transition-group/blob/1fd4a65ac45edd2aea3dec18eeb8b9c07c7eb93f/CHANGELOG.md#440-2020-05-05).

I have created a patch that appears to be working with no warnings or errors. You can see all of what I have done in my fork [master branch](https://github.com/jasondana/react-toast-notifications/tree/master).

I am somewhat new to React, so I am not certain if this is the best solution. According to [React's documentation](https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers), adding forwardRef is a major addition and should require a major version change. It also has the side-effect of requiring custom notifications to use the forwardRef like so:

```javascript
const MyCustomToast = React.forwardRef(({ appearance, children }, ref) => (
  <div ref={ref} style=({ background: appearance === 'error' ? 'red' : 'green' })>
    {children}
  </div>
));
```

If I am mistaken or if you or anyone else has a better approach to the solution, please let me know.

**Comment by Hainesy** [comment]
Is there any update on this issue? Being bombarded with these findDOMNode errors.

**Comment by cameronwlewis** [comment]
+1.  This has been a frustrating issue :(

**Comment by smith-it** [comment]
Any update on this?

**Comment by razgraf** [comment]
For everyone still experiencing this, @jasondana had a really good answer [here](https://github.com/jossmac/react-toast-notifications/issues/82#issuecomment-643655257) (for me, only bumping the library version didn't do the trick either). Until the PR gets merged, you could fork a private copy and use that version.

Also, for those using Functional Components, there might also be an issue with `forwardRef` on non-class components. You can get rid of it by wrapping the custom `Toast` element that you pass to the `ToastProvider` into a React.forwardRef(props, ref => </...>).

**Comment by wacanam** [comment]
issue still occur. 

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by ToastElement)
    in ToastElement (created by DefaultToast)
    in DefaultToast (created by ToastController)
    in ToastController (created by Transition)
    in Transition (created by ToastProvider)
    in TransitionGroup (created by ToastProvider)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by ToastContainer)
    in ToastContainer (created by ToastProvider)
    in ToastProvider (at App.js:28)
    in CookiesProvider (at App.js:26)
    in App (at src/index.js:11)
    in StrictMode (at src/index.js:10)
```

**Comment by pA1nD** [comment]
@wacanam check out the repo from @jasondana above! This one actually works fine.

I've use this repo and made a small change so you can directly add it in your npm modules folder.

It is currently up to date with this repo, but I will not update it. Instead you should check, once the issue has actually been fixed.

### Here is how to use it:

In your `package.json` and find the `react-toast-notifications`. Replace it with:
```
    "react-toast-notifications": "git+https://github.com/pA1nD/react-toast-notifications.git",
```

Then run `rm -rf node_modules && npm i` to be sure that the hotfixed version is installed.

Finally make sure to restart your dev server, it should work now.

### To use a custom Toast with Typescript, see this example:

```
import React from 'react'
import { ToastProps } from 'react-toast-notifications'

const Toast = React.forwardRef<HTMLDivElement, ToastProps>(({ appearance, children }, ref) => {
  return (
    <div ref={ref} style={{ background: appearance === 'error' ? 'red' : 'green' }}>
      {children}
    </div>
  )
})

export default Toast

```

**Comment by jossmac** [comment]
Resolved by #116 -- available from `2.4.3`

**Comment by heldtogether** [comment]
I've updated to 2.4.3 but I'm still seeing the warning. Is there another step required to resolve?

**Comment by jossmac** [comment]
@heldtogether 

> I've updated to 2.4.3 but I'm still seeing the warning. Is there another step required to resolve?

Run `yarn` or `npm install` from root?

**Comment by heldtogether** [comment]
Update: see the console of this codesandbox for the warning still being present with 2.4.3: https://codesandbox.io/s/toast-c3c1j?file=/src/App.js

**Comment by FLAME878** [comment]
I am also having this issue even though I've updated to 2.4.3

**Comment by jossmac** [comment]
Sorry folks, I misunderstood. Updating react-transition-group doesn't solve the issue, it just provides a workaround that can be implemented. I'll need to rewrite a bunch of stuff to support ref forwarding

**Comment by hutber** [comment]
I believe sadly then, we'll need to avoid this repo until its fixed :(

**Comment by fedecaccia** [comment]
This fix actually solves the issue https://github.com/jossmac/react-toast-notifications/issues/82#issuecomment-727132660

**Comment by everdrone** [comment]
Can we merge the fix from the repo mentioned in https://github.com/jossmac/react-toast-notifications/issues/82#issuecomment-727132660?
Having a git repository as a source `package.json` might break things in the future
